"""模板管理

Revision ID: 05792ba825b0
Revises: 59eb93578246
Create Date: 2025-12-06 12:16:41.667529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05792ba825b0'
down_revision: Union[str, Sequence[str], None] = '59eb93578246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 安全地删除表和索引（如果存在）
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # 先删除依赖表（document_management_documents），因为它有外键依赖 document_management_templates
    if 'document_management_documents' in inspector.get_table_names():
        # 获取表的所有索引
        indexes = [idx['name'] for idx in inspector.get_indexes('document_management_documents')]
        
        # 安全地删除索引（如果存在）
        # 尝试删除所有可能的索引名称（包括带前缀和不带前缀的）
        possible_index_names = [
            'idx_dm_documents_name',
            'idx_dm_documents_status',
            'idx_dm_documents_template_id',
            'ix_document_management_documents_id',
        ]
        # 添加 op.f() 生成的名称（如果存在）
        for name in ['idx_dm_documents_name', 'idx_dm_documents_status', 'idx_dm_documents_template_id', 'ix_document_management_documents_id']:
            f_name = op.f(name)
            if f_name and f_name not in possible_index_names:
                possible_index_names.append(f_name)
        
        for idx_name in possible_index_names:
            if idx_name and idx_name in indexes:
                try:
                    op.drop_index(idx_name, table_name='document_management_documents')
                except Exception:
                    # 如果删除失败（可能已经被删除或名称不匹配），继续
                    pass
        
        # 删除表
        try:
            op.drop_table('document_management_documents')
        except Exception:
            # 如果表不存在，继续
            pass
    
    # 然后删除被依赖的表（document_management_templates）
    if 'document_management_templates' in inspector.get_table_names():
        # 获取表的所有索引
        indexes = [idx['name'] for idx in inspector.get_indexes('document_management_templates')]
        
        # 安全地删除索引（如果存在）
        # 尝试删除所有可能的索引名称（包括带前缀和不带前缀的）
        possible_index_names = [
            'idx_dm_templates_category',
            'idx_dm_templates_name',
            'idx_dm_templates_status',
            'ix_document_management_templates_id',
        ]
        # 添加 op.f() 生成的名称（如果存在）
        for name in ['idx_dm_templates_category', 'idx_dm_templates_name', 'idx_dm_templates_status', 'ix_document_management_templates_id']:
            f_name = op.f(name)
            if f_name and f_name not in possible_index_names:
                possible_index_names.append(f_name)
        
        for idx_name in possible_index_names:
            if idx_name and idx_name in indexes:
                try:
                    op.drop_index(idx_name, table_name='document_management_templates')
                except Exception:
                    # 如果删除失败（可能已经被删除或名称不匹配），继续
                    pass
        
        # 删除表
        try:
            op.drop_table('document_management_templates')
        except Exception:
            # 如果表不存在，继续
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_management_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='关联的模板ID'),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='文书名称'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='文书描述'),
    sa.Column('form_data', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False, comment='占位符填写数据，格式：{name: value}'),
    sa.Column('visual_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='生成的文书视觉JSON，包含填充后的内容和样式'),
    sa.Column('png_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='生成的 PNG 文件在 COS 中的 URL（多页文档可能有多个PNG）'),
    sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='生成的 PDF 文件在 COS 中的 URL'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False, comment='状态：draft/published/archived'),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='创建人ID'),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='更新人ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['staffs.id'], name=op.f('document_management_documents_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['template_id'], ['document_management_templates.id'], name=op.f('document_management_documents_template_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staffs.id'], name=op.f('document_management_documents_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_management_documents_pkey'))
    )
    op.create_index(op.f('ix_document_management_documents_id'), 'document_management_documents', ['id'], unique=False)
    op.create_index(op.f('idx_dm_documents_template_id'), 'document_management_documents', ['template_id'], unique=False)
    op.create_index(op.f('idx_dm_documents_status'), 'document_management_documents', ['status'], unique=False)
    op.create_index(op.f('idx_dm_documents_name'), 'document_management_documents', ['name'], unique=False)
    op.create_table('document_management_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='文书模板名称'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='文书模板描述'),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='分类名称'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False, comment='状态：draft/published'),
    sa.Column('png_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='原始 PNG 模板文件在 COS 中的 URL'),
    sa.Column('visual_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='OCR 解析的视觉JSON，包含完整的样式属性信息'),
    sa.Column('prosemirror_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='ProseMirror JSON 格式的文档内容，从视觉JSON转换而来'),
    sa.Column('ocr_task_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='百度飞桨 OCR 任务 ID'),
    sa.Column('ocr_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='OCR 解析状态：pending/running/success/failure'),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='创建人ID'),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='更新人ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['staffs.id'], name=op.f('document_management_templates_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staffs.id'], name=op.f('document_management_templates_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_management_templates_pkey'))
    )
    op.create_index(op.f('ix_document_management_templates_id'), 'document_management_templates', ['id'], unique=False)
    op.create_index(op.f('idx_dm_templates_status'), 'document_management_templates', ['status'], unique=False)
    op.create_index(op.f('idx_dm_templates_name'), 'document_management_templates', ['name'], unique=False)
    op.create_index(op.f('idx_dm_templates_category'), 'document_management_templates', ['category'], unique=False)
    # ### end Alembic commands ###
