"""add_document_templates_and_generations

Revision ID: 07833b0266b9
Revises: 4c60a924374d
Create Date: 2025-11-15 22:12:56.202561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07833b0266b9'
down_revision: Union[str, Sequence[str], None] = '4c60a924374d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_path', sa.String(length=500), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('placeholder_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_templates_category', 'document_templates', ['category'], unique=False)
    op.create_index('idx_document_templates_name', 'document_templates', ['name'], unique=False)
    op.create_index('idx_document_templates_status', 'document_templates', ['status'], unique=False)
    op.create_index(op.f('ix_document_templates_category'), 'document_templates', ['category'], unique=False)
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    op.create_index(op.f('ix_document_templates_name'), 'document_templates', ['name'], unique=False)
    op.create_index(op.f('ix_document_templates_status'), 'document_templates', ['status'], unique=False)
    op.create_table('document_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('document_filename', sa.String(length=200), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_generations_generated_at', 'document_generations', ['generated_at'], unique=False)
    op.create_index('idx_document_generations_generated_by', 'document_generations', ['generated_by'], unique=False)
    op.create_index('idx_document_generations_template_id', 'document_generations', ['template_id'], unique=False)
    op.create_index(op.f('ix_document_generations_generated_by'), 'document_generations', ['generated_by'], unique=False)
    op.create_index(op.f('ix_document_generations_id'), 'document_generations', ['id'], unique=False)
    op.create_index(op.f('ix_document_generations_template_id'), 'document_generations', ['template_id'], unique=False)
    op.alter_column('cases', 'loan_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'loan_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_document_generations_template_id'), table_name='document_generations')
    op.drop_index(op.f('ix_document_generations_id'), table_name='document_generations')
    op.drop_index(op.f('ix_document_generations_generated_by'), table_name='document_generations')
    op.drop_index('idx_document_generations_template_id', table_name='document_generations')
    op.drop_index('idx_document_generations_generated_by', table_name='document_generations')
    op.drop_index('idx_document_generations_generated_at', table_name='document_generations')
    op.drop_table('document_generations')
    op.drop_index(op.f('ix_document_templates_status'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_name'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_id'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_category'), table_name='document_templates')
    op.drop_index('idx_document_templates_status', table_name='document_templates')
    op.drop_index('idx_document_templates_name', table_name='document_templates')
    op.drop_index('idx_document_templates_category', table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
