"""EvidenceCard

Revision ID: 08ef159b2321
Revises: f115beb00e7c
Create Date: 2025-11-03 15:06:50.896330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08ef159b2321'
down_revision: Union[str, Sequence[str], None] = 'f115beb00e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_times', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_cards_id'), 'evidence_cards', ['id'], unique=False)
    op.create_table('evidence_card_evidence_association',
    sa.Column('evidence_card_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_card_id'], ['evidence_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_card_id', 'evidence_id')
    )
    # 使用 IF EXISTS 删除表和索引（如果不存在则忽略错误）
    op.execute("DROP TABLE IF EXISTS template_fields CASCADE")
    op.execute("DROP TABLE IF EXISTS document_templates CASCADE")
    op.execute("DROP TABLE IF EXISTS generated_documents CASCADE")
    
    # 使用 IF EXISTS 删除枚举类型（如果不存在则忽略错误）
    op.execute("DROP TYPE IF EXISTS documenttemplatetype")
    op.execute("DROP TYPE IF EXISTS documenttemplatestatus")
    op.execute("DROP TYPE IF EXISTS templatefieldlevel")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('title', 'secondary_title', 'tertiary_title', 'field', name='templatefieldlevel').create(op.get_bind())
    sa.Enum('draft', 'active', 'archived', name='documenttemplatestatus').create(op.get_bind())
    sa.Enum('lawsuit', 'withdrawal', 'evidence_application', 'enforcement_application', 'power_of_attorney', 'other', name='documenttemplatetype').create(op.get_bind())
    op.create_table('generated_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rendered_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_signed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('signed_file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('generated_documents_case_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['staffs.id'], name=op.f('generated_documents_created_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('generated_documents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_documents_pkey'))
    )
    op.create_index(op.f('ix_generated_documents_id'), 'generated_documents', ['id'], unique=False)
    op.create_table('document_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_type', postgresql.ENUM('lawsuit', 'withdrawal', 'evidence_application', 'enforcement_application', 'power_of_attorney', 'other', name='documenttemplatetype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'active', 'archived', name='documenttemplatestatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('template_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parsed_structure', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('field_mappings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staffs.id'], name=op.f('document_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['staffs.id'], name=op.f('document_templates_template_type_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['staffs.id'], name=op.f('document_templates_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_templates_pkey'))
    )
    op.create_index(op.f('ix_document_templates_name'), 'document_templates', ['name'], unique=False)
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    op.create_table('template_fields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('field_level', postgresql.ENUM('title', 'secondary_title', 'tertiary_title', 'field', name='templatefieldlevel', create_type=False), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=50), server_default=sa.text("'text'::character varying"), autoincrement=False, nullable=False),
    sa.Column('required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('default_value', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('placeholder', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('template_fields_pkey'))
    )
    op.create_index(op.f('ix_template_fields_id'), 'template_fields', ['id'], unique=False)
    op.drop_table('evidence_card_evidence_association')
    op.drop_index(op.f('ix_evidence_cards_id'), table_name='evidence_cards')
    op.drop_table('evidence_cards')
    # ### end Alembic commands ###
