"""add_analysis_report_trigger_metadata

Revision ID: 0babbc30c211
Revises: 46254f8a6f5f
Create Date: 2026-01-13 14:08:33.652031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0babbc30c211'
down_revision: Union[str, Sequence[str], None] = '46254f8a6f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_analysis_reports', sa.Column('trigger_type', sa.String(length=30), nullable=False))
    op.add_column('case_analysis_reports', sa.Column('ref_commit_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('case_analysis_reports', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('case_analysis_reports', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('case_analysis_reports', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('case_analysis_reports', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_analysis_reports', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('case_analysis_reports', 'completed_at')
    op.drop_column('case_analysis_reports', 'error_message')
    op.drop_column('case_analysis_reports', 'status')
    op.drop_column('case_analysis_reports', 'ref_commit_ids')
    op.drop_column('case_analysis_reports', 'trigger_type')
    # ### end Alembic commands ###
