"""DocumentTemplate Add

Revision ID: 0e5543a77f24
Revises: 4c60a924374d
Create Date: 2025-11-18 22:00:46.714778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5543a77f24'
down_revision: Union[str, Sequence[str], None] = '4c60a924374d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='文书模板名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='文书模板描述'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='分类名称'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：draft/published'),
    sa.Column('prosemirror_json', sa.JSON(), nullable=False, comment='ProseMirror JSON 格式的文档内容'),
    sa.Column('docx_url', sa.String(length=500), nullable=True, comment='原始 DOCX 文件在 COS 中的 URL'),
    sa.Column('placeholders', sa.JSON(), nullable=True, comment="占位符信息，格式：{'placeholders': ['name', 'date'], 'metadata': {...}}"),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_templates_category', 'document_templates', ['category'], unique=False)
    op.create_index('idx_document_templates_name', 'document_templates', ['name'], unique=False)
    op.create_index('idx_document_templates_status', 'document_templates', ['status'], unique=False)
    op.create_index(op.f('ix_document_templates_category'), 'document_templates', ['category'], unique=False)
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    op.create_index(op.f('ix_document_templates_name'), 'document_templates', ['name'], unique=False)
    op.create_index(op.f('ix_document_templates_status'), 'document_templates', ['status'], unique=False)
    op.alter_column('cases', 'loan_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'loan_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_document_templates_status'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_name'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_id'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_category'), table_name='document_templates')
    op.drop_index('idx_document_templates_status', table_name='document_templates')
    op.drop_index('idx_document_templates_name', table_name='document_templates')
    op.drop_index('idx_document_templates_category', table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
