"""init models

Revision ID: 133758b1b9d4
Revises: 
Create Date: 2025-07-21 13:38:44.914745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '133758b1b9d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查并创建 casestatus 枚举类型
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT typname FROM pg_type WHERE typname = 'casestatus'"
    ))
    if result.fetchone() is None:
        sa.Enum('DRAFT', 'INFO_ENTERED', 'EVIDENCE_ANNOTATED', 'DOCUMENTS_GENERATED', name='casestatus').create(conn)

    # 检查并创建 casetype 枚举类型
    result = conn.execute(sa.text(
        "SELECT typname FROM pg_type WHERE typname = 'casetype'"
    ))
    if result.fetchone() is None:
        sa.Enum('DEBT', 'CONTRACT', name='casetype').create(conn)
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staffs_id'), 'staffs', ['id'], unique=False)
    op.create_index(op.f('ix_staffs_username'), 'staffs', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_card', sa.String(length=18), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_id_card'), 'users', ['id_card'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_type', postgresql.ENUM('DEBT', 'CONTRACT', name='casetype', create_type=False), nullable=True),
    sa.Column('case_status', postgresql.ENUM('DRAFT', 'INFO_ENTERED', 'EVIDENCE_ANNOTATED', 'DOCUMENTS_GENERATED', name='casestatus', create_type=False), nullable=False),
    sa.Column('creditor_name', sa.String(length=50), nullable=False),
    sa.Column('debtor_name', sa.String(length=50), nullable=True),
    sa.Column('creditor_type', sa.String(length=50), nullable=True),
    sa.Column('debtor_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_creditor_name'), 'cases', ['creditor_name'], unique=False)
    op.create_index(op.f('ix_cases_debtor_name'), 'cases', ['debtor_name'], unique=False)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('evidence_status', sa.String(length=20), nullable=False),
    sa.Column('classification_category', sa.String(length=50), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features_extracted_at', sa.DateTime(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_id'), 'evidences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidences_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_debtor_name'), table_name='cases')
    op.drop_index(op.f('ix_cases_creditor_name'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id_card'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_staffs_username'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_id'), table_name='staffs')
    op.drop_table('staffs')
    # 安全地删除枚举类型（先检查是否存在）
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT typname FROM pg_type WHERE typname = 'casetype'"
    ))
    if result.fetchone() is not None:
        sa.Enum('DEBT', 'CONTRACT', name='casetype').drop(conn)
    result = conn.execute(sa.text(
        "SELECT typname FROM pg_type WHERE typname = 'casestatus'"
    ))
    if result.fetchone() is not None:
        sa.Enum('DRAFT', 'INFO_ENTERED', 'EVIDENCE_ANNOTATED', 'DOCUMENTS_GENERATED', name='casestatus').drop(conn)
    # ### end Alembic commands ###
