"""add AssociationEvidenceFeature

Revision ID: 175b19a75283
Revises: 133758b1b9d4
Create Date: 2025-07-28 16:52:50.838189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '175b19a75283'
down_revision: Union[str, Sequence[str], None] = '133758b1b9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_evidence_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_group_name', sa.String(length=50), nullable=False),
    sa.Column('association_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_feature_status', sa.String(length=20), nullable=False),
    sa.Column('evidence_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features_extracted_at', sa.DateTime(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_association_evidence_features_id'), 'association_evidence_features', ['id'], unique=False)
    # 添加validation_status列（先允许NULL，然后设置默认值，最后改为NOT NULL）
    op.add_column('evidences', sa.Column('validation_status', sa.String(length=20), nullable=True))
    op.execute("UPDATE evidences SET validation_status = 'pending' WHERE validation_status IS NULL")
    op.alter_column('evidences', 'validation_status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidences', 'validation_status')
    op.drop_index(op.f('ix_association_evidence_features_id'), table_name='association_evidence_features')
    op.drop_table('association_evidence_features')
    # ### end Alembic commands ###
