"""add_evidence_classification_fields

Revision ID: 2c3f28c25ed5
Revises: b7a8a690625a
Create Date: 2025-07-13 20:06:42.252273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c3f28c25ed5'
down_revision: Union[str, Sequence[str], None] = 'b7a8a690625a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidences', sa.Column('evidence_type', sa.String(length=50), nullable=True))
    op.add_column('evidences', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('evidences', sa.Column('classification_reasoning', sa.Text(), nullable=True))
    op.add_column('evidences', sa.Column('is_classified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidences', 'is_classified')
    op.drop_column('evidences', 'classification_reasoning')
    op.drop_column('evidences', 'classification_confidence')
    op.drop_column('evidences', 'evidence_type')
    # ### end Alembic commands ###
