"""业务模型更新

Revision ID: 387c4c988711
Revises: b10afb45abfe
Create Date: 2025-07-09 17:42:04.730248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '387c4c988711'
down_revision: Union[str, Sequence[str], None] = 'b10afb45abfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PERSON', 'COMPANY', 'INDIVIDUAL', name='partytype').create(op.get_bind())
    op.add_column('cases', sa.Column('creaditor_name', sa.String(length=50), nullable=False))
    op.add_column('cases', sa.Column('creditor_type', postgresql.ENUM('PERSON', 'COMPANY', 'INDIVIDUAL', name='partytype', create_type=False), nullable=True))
    op.add_column('cases', sa.Column('debtor_name', sa.String(length=50), nullable=False))
    op.add_column('cases', sa.Column('debtor_type', postgresql.ENUM('PERSON', 'COMPANY', 'INDIVIDUAL', name='partytype', create_type=False), nullable=True))
    op.create_index(op.f('ix_cases_creaditor_name'), 'cases', ['creaditor_name'], unique=False)
    op.create_index(op.f('ix_cases_debtor_name'), 'cases', ['debtor_name'], unique=False)
    op.drop_column('cases', 'start_date')
    op.drop_column('cases', 'end_date')
    op.drop_column('cases', 'status')
    op.drop_index(op.f('ix_evidences_title'), table_name='evidences')
    op.drop_column('evidences', 'description')
    op.drop_column('evidences', 'title')
    op.drop_column('evidences', 'evidence_type')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'address')
    op.drop_column('users', 'is_active')
    sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='casestatus').drop(op.get_bind())
    sa.Enum('DOCUMENT', 'IMAGE', 'AUDIO', 'VIDEO', 'OTHER', name='evidencetype').drop(op.get_bind())
    op.sync_enum_values(
        enum_schema='public',
        enum_name='casetype',
        new_values=['DEBT', 'CONTRACT'],
        affected_columns=[TableReference(table_schema='public', table_name='cases', column_name='case_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='casetype',
        new_values=['DEBT', 'CONTRACT', 'OTHER'],
        affected_columns=[TableReference(table_schema='public', table_name='cases', column_name='case_type')],
        enum_values_to_rename=[],
    )
    sa.Enum('DOCUMENT', 'IMAGE', 'AUDIO', 'VIDEO', 'OTHER', name='evidencetype').create(op.get_bind())
    sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='casestatus').create(op.get_bind())
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('evidences', sa.Column('evidence_type', postgresql.ENUM('DOCUMENT', 'IMAGE', 'AUDIO', 'VIDEO', 'OTHER', name='evidencetype', create_type=False), autoincrement=False, nullable=False))
    op.add_column('evidences', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('evidences', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_evidences_title'), 'evidences', ['title'], unique=False)
    op.add_column('cases', sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='casestatus', create_type=False), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cases_debtor_name'), table_name='cases')
    op.drop_index(op.f('ix_cases_creaditor_name'), table_name='cases')
    op.drop_column('cases', 'debtor_type')
    op.drop_column('cases', 'debtor_name')
    op.drop_column('cases', 'creditor_type')
    op.drop_column('cases', 'creaditor_name')
    sa.Enum('PERSON', 'COMPANY', 'INDIVIDUAL', name='partytype').drop(op.get_bind())
    # ### end Alembic commands ###
