"""修改占位符唯一逻辑为(name, type)

Revision ID: 3e318138779a
Revises: e6f347101834
Create Date: 2025-11-22 13:18:30.898145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e318138779a'
down_revision: Union[str, Sequence[str], None] = 'e6f347101834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_generations', 'form_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='占位符填写数据，格式：{name: value}',
               existing_comment='占位符填写数据，格式：{placeholder_name: value}',
               existing_nullable=False)
    op.alter_column('template_placeholders', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='占位符名称（如：{{姓名}} 对应 name 字段）',
               existing_comment='占位符名称（唯一，如：{{姓名}} 对应 name 字段）',
               existing_nullable=False)
    op.drop_index('ix_template_placeholders_name', table_name='template_placeholders')
    op.create_index(op.f('ix_template_placeholders_name'), 'template_placeholders', ['name'], unique=False)
    op.create_index(op.f('ix_template_placeholders_type'), 'template_placeholders', ['type'], unique=False)
    op.create_unique_constraint('uq_template_placeholders_name_type', 'template_placeholders', ['name', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_template_placeholders_name_type', 'template_placeholders', type_='unique')
    op.drop_index(op.f('ix_template_placeholders_type'), table_name='template_placeholders')
    op.drop_index(op.f('ix_template_placeholders_name'), table_name='template_placeholders')
    op.create_index('ix_template_placeholders_name', 'template_placeholders', ['name'], unique=False)
    op.alter_column('template_placeholders', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='占位符名称（唯一，如：{{姓名}} 对应 name 字段）',
               existing_comment='占位符名称（如：{{姓名}} 对应 name 字段）',
               existing_nullable=False)
    op.alter_column('document_generations', 'form_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='占位符填写数据，格式：{placeholder_name: value}',
               existing_comment='占位符填写数据，格式：{name: value}',
               existing_nullable=False)
    # ### end Alembic commands ###
