"""add_case_id_to_evidence_cards

Revision ID: 4c60a924374d
Revises: fc24043d1138
Create Date: 2025-11-06 15:44:36.302550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c60a924374d'
down_revision: Union[str, Sequence[str], None] = 'fc24043d1138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空的 case_id 列
    op.add_column('evidence_cards', sa.Column('case_id', sa.Integer(), nullable=True, comment='关联的案件ID'))
    
    # 为现有数据设置 case_id（从关联的证据中获取）
    # 对于每个卡片，从其 evidence_ids 中获取第一个存在的证据的 case_id
    op.execute("""
        UPDATE evidence_cards
        SET case_id = (
            SELECT e.case_id
            FROM evidences e
            WHERE e.id = ANY(
                SELECT jsonb_array_elements_text(evidence_cards.evidence_ids::jsonb)::int
            )
            LIMIT 1
        )
        WHERE case_id IS NULL
    """)
    
    # 将 case_id 设置为 NOT NULL
    op.alter_column('evidence_cards', 'case_id', nullable=False)
    
    # 创建索引和外键
    op.create_index(op.f('ix_evidence_cards_case_id'), 'evidence_cards', ['case_id'], unique=False)
    op.create_foreign_key('fk_evidence_cards_case_id', 'evidence_cards', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_evidence_cards_case_id', 'evidence_cards', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_cards_case_id'), table_name='evidence_cards')
    op.drop_column('evidence_cards', 'case_id')
    # ### end Alembic commands ###
