"""新增占位符适用于模板类型属性

Revision ID: 59eb93578246
Revises: 3e318138779a
Create Date: 2025-11-22 13:34:44.944458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59eb93578246'
down_revision: Union[str, Sequence[str], None] = '3e318138779a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_placeholders', sa.Column('applicable_template_category', sa.String(length=100), nullable=True, comment='适用的模板类型：要素式/陈述式/通用（None表示通用，适用于所有类型）'))
    op.drop_constraint('uq_template_placeholders_name_type', 'template_placeholders', type_='unique')
    op.create_index(op.f('ix_template_placeholders_applicable_template_category'), 'template_placeholders', ['applicable_template_category'], unique=False)
    op.create_unique_constraint('uq_template_placeholders_name_category', 'template_placeholders', ['name', 'applicable_template_category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_template_placeholders_name_category', 'template_placeholders', type_='unique')
    op.drop_index(op.f('ix_template_placeholders_applicable_template_category'), table_name='template_placeholders')
    op.create_unique_constraint('uq_template_placeholders_name_type', 'template_placeholders', ['name', 'type'])
    op.drop_column('template_placeholders', 'applicable_template_category')
    # ### end Alembic commands ###
