"""add_status_and_placeholder_metadata_to_documents

Revision ID: 757f90a74811
Revises: 0256cace79e6
Create Date: 2025-12-06 16:18:53.576072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757f90a74811'
down_revision: Union[str, Sequence[str], None] = '0256cace79e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加 status 字段，允许为空
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=True, comment='状态：draft（草稿）/published（发布）'))
    # 为现有记录设置默认值
    op.execute("UPDATE documents SET status = 'draft' WHERE status IS NULL")
    # 然后设置为非空
    op.alter_column('documents', 'status', nullable=False, server_default='draft')
    # 添加 placeholder_metadata 字段
    op.add_column('documents', sa.Column('placeholder_metadata', sa.JSON(), nullable=True, comment='占位符元数据，格式：{"placeholder_name": {"name": "...", "type": "text|radio|checkbox", "options": [...]}}'))
    # 创建索引
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_column('documents', 'placeholder_metadata')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
