"""add evidence_role to evidence

Revision ID: 7bf3c8dae826
Revises: b0b5adb883e1
Create Date: 2025-08-25 13:43:45.047507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf3c8dae826'
down_revision: Union[str, Sequence[str], None] = 'b0b5adb883e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidences', sa.Column('evidence_role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidences', 'evidence_role')
    # ### end Alembic commands ###
