"""Make external_contacts.staff_id nullable

Revision ID: 87a8a74ff1f5
Revises: a3a488e20504
Create Date: 2025-09-07 19:30:22.185637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a8a74ff1f5'
down_revision: Union[str, Sequence[str], None] = 'a3a488e20504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_ways', 'callback_enabled')
    op.drop_constraint('external_contacts_staff_id_fkey', 'external_contacts', type_='foreignkey')
    op.drop_column('external_contacts', 'staff_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_contacts', sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('external_contacts_staff_id_fkey', 'external_contacts', 'we_com_staffs', ['staff_id'], ['id'])
    op.add_column('contact_ways', sa.Column('callback_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
