"""add_content_json_to_document_drafts

Revision ID: a051e30d97c5
Revises: b601aaacfff1
Create Date: 2025-12-08 12:06:52.135344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a051e30d97c5'
down_revision: Union[str, Sequence[str], None] = 'b601aaacfff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_drafts', sa.Column('content_json', sa.JSON(), nullable=True, comment='ProseMirror JSON 格式的文档内容，存储完整的文档内容副本'))
    op.alter_column('document_drafts', 'form_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='表单数据，格式：{"placeholder_name": "value"}（已废弃，新功能使用 content_json）',
               existing_comment='表单数据，格式：{"placeholder_name": "value"}',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_drafts', 'form_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='表单数据，格式：{"placeholder_name": "value"}',
               existing_comment='表单数据，格式：{"placeholder_name": "value"}（已废弃，新功能使用 content_json）',
               existing_nullable=False)
    op.drop_column('document_drafts', 'content_json')
    # ### end Alembic commands ###
