"""add callback_enabled to contact_way

Revision ID: a3a488e20504
Revises: 1451c7967396
Create Date: 2025-09-07 16:37:50.169204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a488e20504'
down_revision: Union[str, Sequence[str], None] = '1451c7967396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_ways', sa.Column('callback_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_ways', 'callback_enabled')
    # ### end Alembic commands ###
