"""update Case model

Revision ID: a52fdcbe18c1
Revises: 175b19a75283
Create Date: 2025-07-29 09:50:02.180011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52fdcbe18c1'
down_revision: Union[str, Sequence[str], None] = '175b19a75283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('loan_amount', sa.Float(), nullable=True))
    
    # 为现有数据设置默认值
    # 1. 为loan_amount设置默认值0.0
    op.execute("UPDATE cases SET loan_amount = 0.0 WHERE loan_amount IS NULL")
    
    # 2. 为debtor_name设置默认值，处理所有空值情况
    op.execute("UPDATE cases SET debtor_name = '未知债务人' WHERE debtor_name IS NULL OR debtor_name = '' OR debtor_name = 'EMPTY' OR TRIM(debtor_name) = ''")
    
    # 3. 为association_evidence_features表的validation_status设置默认值
    op.execute("UPDATE association_evidence_features SET validation_status = 'pending' WHERE validation_status IS NULL")
    
    # 5. 添加非空约束
    op.alter_column('cases', 'debtor_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cases', 'loan_amount',
               existing_type=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'debtor_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('cases', 'loan_amount')
    # ### end Alembic commands ###
