"""add CaseParty

Revision ID: af2f480a6005
Revises: 7bf3c8dae826
Create Date: 2025-09-02 13:59:56.111309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2f480a6005'
down_revision: Union[str, Sequence[str], None] = '7bf3c8dae826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_partys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_name', sa.String(length=50), nullable=False),
    sa.Column('party_role', sa.String(length=50), nullable=False),
    sa.Column('party_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('nation', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('id_card', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=50), nullable=True),
    sa.Column('company_address', sa.String(length=50), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=50), nullable=True),
    sa.Column('bank_address', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('bank_phone', sa.String(length=50), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_partys_id'), 'case_partys', ['id'], unique=False)
    op.create_index(op.f('ix_case_partys_party_name'), 'case_partys', ['party_name'], unique=False)
    op.drop_index(op.f('ix_cases_creditor_name'), table_name='cases')
    op.drop_index(op.f('ix_cases_debtor_name'), table_name='cases')
    op.drop_column('cases', 'debtor_phone')
    op.drop_column('cases', 'debtor_name')
    op.drop_column('cases', 'creditor_phone')
    op.drop_column('cases', 'creditor_name')
    op.drop_column('cases', 'debtor_type')
    op.drop_column('cases', 'creditor_type')
    op.drop_column('cases', 'creditor_bank_account')
    op.drop_column('cases', 'creditor_bank_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('creditor_bank_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('creditor_bank_account', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('creditor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('debtor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('creditor_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('creditor_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('debtor_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('debtor_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_cases_debtor_name'), 'cases', ['debtor_name'], unique=False)
    op.create_index(op.f('ix_cases_creditor_name'), 'cases', ['creditor_name'], unique=False)
    op.drop_index(op.f('ix_case_partys_party_name'), table_name='case_partys')
    op.drop_index(op.f('ix_case_partys_id'), table_name='case_partys')
    op.drop_table('case_partys')
    # ### end Alembic commands ###
