"""update User & Case model

Revision ID: b0b5adb883e1
Revises: 8ad9b7c0cc48
Create Date: 2025-08-14 10:07:02.588830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b5adb883e1'
down_revision: Union[str, Sequence[str], None] = '8ad9b7c0cc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('creditor_phone', sa.String(length=50), nullable=True))
    op.add_column('cases', sa.Column('creditor_bank_account', sa.String(length=50), nullable=True))
    op.add_column('cases', sa.Column('creditor_bank_address', sa.String(length=50), nullable=True))
    op.add_column('cases', sa.Column('debtor_phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('wechat_nickname', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('wechat_number', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('wechat_avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wechat_avatar')
    op.drop_column('users', 'wechat_number')
    op.drop_column('users', 'wechat_nickname')
    op.drop_column('cases', 'debtor_phone')
    op.drop_column('cases', 'creditor_bank_address')
    op.drop_column('cases', 'creditor_bank_account')
    op.drop_column('cases', 'creditor_phone')
    # ### end Alembic commands ###
