"""document_drafts

Revision ID: b601aaacfff1
Revises: 757f90a74811
Create Date: 2025-12-07 23:17:49.430492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b601aaacfff1'
down_revision: Union[str, Sequence[str], None] = '757f90a74811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False, comment='案件ID'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='模板ID'),
    sa.Column('form_data', sa.JSON(), nullable=False, comment='表单数据，格式：{"placeholder_name": "value"}'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='最后更新人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'document_id', name='uq_document_drafts_case_document')
    )
    op.create_index('idx_document_drafts_case_document', 'document_drafts', ['case_id', 'document_id'], unique=False)
    op.create_index('idx_document_drafts_case_id', 'document_drafts', ['case_id'], unique=False)
    op.create_index('idx_document_drafts_document_id', 'document_drafts', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_drafts_case_id'), 'document_drafts', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_drafts_document_id'), 'document_drafts', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_drafts_id'), 'document_drafts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_drafts_id'), table_name='document_drafts')
    op.drop_index(op.f('ix_document_drafts_document_id'), table_name='document_drafts')
    op.drop_index(op.f('ix_document_drafts_case_id'), table_name='document_drafts')
    op.drop_index('idx_document_drafts_document_id', table_name='document_drafts')
    op.drop_index('idx_document_drafts_case_id', table_name='document_drafts')
    op.drop_index('idx_document_drafts_case_document', table_name='document_drafts')
    op.drop_table('document_drafts')
    # ### end Alembic commands ###
