"""TemplatePlaceholder Add

Revision ID: bbe23883ef56
Revises: 0e5543a77f24
Create Date: 2025-11-18 23:57:36.141781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbe23883ef56'
down_revision: Union[str, Sequence[str], None] = '0e5543a77f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_placeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placeholder_name', sa.String(length=100), nullable=False, comment='占位符名称（唯一，如：name, date, creditor_gender）'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='占位符类型：text, textarea, select, radio, checkbox, date, number, file'),
    sa.Column('required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('hint', sa.Text(), nullable=True, comment='提示文本'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选项列表（用于 select, radio, checkbox 类型）'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_placeholders_placeholder_name', 'template_placeholders', ['placeholder_name'], unique=False)
    op.create_index(op.f('ix_template_placeholders_id'), 'template_placeholders', ['id'], unique=False)
    op.create_index(op.f('ix_template_placeholders_placeholder_name'), 'template_placeholders', ['placeholder_name'], unique=True)
    op.create_table('template_placeholder_associations',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('placeholder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['placeholder_id'], ['template_placeholders.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'placeholder_id')
    )
    op.create_index('idx_template_placeholder_placeholder_id', 'template_placeholder_associations', ['placeholder_id'], unique=False)
    op.create_index('idx_template_placeholder_template_id', 'template_placeholder_associations', ['template_id'], unique=False)
    op.drop_column('document_templates', 'placeholders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_templates', sa.Column('placeholders', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="占位符信息，格式：{'placeholders': ['name', 'date'], 'metadata': {...}}"))
    op.drop_index('idx_template_placeholder_template_id', table_name='template_placeholder_associations')
    op.drop_index('idx_template_placeholder_placeholder_id', table_name='template_placeholder_associations')
    op.drop_table('template_placeholder_associations')
    op.drop_index(op.f('ix_template_placeholders_placeholder_name'), table_name='template_placeholders')
    op.drop_index(op.f('ix_template_placeholders_id'), table_name='template_placeholders')
    op.drop_index('idx_template_placeholders_placeholder_name', table_name='template_placeholders')
    op.drop_table('template_placeholders')
    # ### end Alembic commands ###
