"""Add video creation tables

Revision ID: c82852a8faff
Revises: 0babbc30c211
Create Date: 2026-01-19 18:07:44.408188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c82852a8faff'
down_revision: Union[str, Sequence[str], None] = '0babbc30c211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('A_CASE', 'B_MISCONCEPTION', 'C_GAP', name='scripttype').create(op.get_bind())
    sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole').create(op.get_bind())
    op.create_table('video_creation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_creation_sessions_id'), 'video_creation_sessions', ['id'], unique=False)
    op.create_table('video_creation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['video_creation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_creation_messages_id'), 'video_creation_messages', ['id'], unique=False)
    op.create_table('video_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('script_type', postgresql.ENUM('A_CASE', 'B_MISCONCEPTION', 'C_GAP', name='scripttype', create_type=False), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('source_article_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['video_creation_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['video_creation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_scripts_id'), 'video_scripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_scripts_id'), table_name='video_scripts')
    op.drop_table('video_scripts')
    op.drop_index(op.f('ix_video_creation_messages_id'), table_name='video_creation_messages')
    op.drop_table('video_creation_messages')
    op.drop_index(op.f('ix_video_creation_sessions_id'), table_name='video_creation_sessions')
    op.drop_table('video_creation_sessions')
    sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole').drop(op.get_bind())
    sa.Enum('A_CASE', 'B_MISCONCEPTION', 'C_GAP', name='scripttype').drop(op.get_bind())
    # ### end Alembic commands ###
