"""remove_legacy_modules

Revision ID: cdf7c7ce28ee
Revises: f1234567890a
Create Date: 2025-12-13 09:26:24.464065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdf7c7ce28ee'
down_revision: Union[str, Sequence[str], None] = 'f1234567890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop usage tables first
    op.drop_index('idx_template_placeholder_placeholder_id', table_name='template_placeholder_associations')
    op.drop_index('idx_template_placeholder_template_id', table_name='template_placeholder_associations')
    op.drop_table('template_placeholder_associations')
    
    op.drop_index('idx_document_generations_case_id', table_name='document_generations')
    op.drop_index('idx_document_generations_template_id', table_name='document_generations')
    op.drop_index('ix_document_generations_case_id', table_name='document_generations')
    op.drop_index('ix_document_generations_id', table_name='document_generations')
    op.drop_index('ix_document_generations_template_id', table_name='document_generations')
    op.drop_table('document_generations')
    
    # Drop definition tables last
    op.drop_index('idx_document_templates_category', table_name='document_templates')
    op.drop_index('idx_document_templates_name', table_name='document_templates')
    op.drop_index('idx_document_templates_status', table_name='document_templates')
    op.drop_index('ix_document_templates_category', table_name='document_templates')
    op.drop_index('ix_document_templates_id', table_name='document_templates')
    op.drop_index('ix_document_templates_name', table_name='document_templates')
    op.drop_index('ix_document_templates_status', table_name='document_templates')
    op.drop_table('document_templates')
    
    op.drop_index('idx_template_placeholders_name', table_name='template_placeholders')
    op.drop_index('ix_template_placeholders_applicable_template_category', table_name='template_placeholders')
    op.drop_index('ix_template_placeholders_id', table_name='template_placeholders')
    op.drop_index('ix_template_placeholders_name', table_name='template_placeholders')
    op.drop_index('ix_template_placeholders_type', table_name='template_placeholders')
    op.drop_table('template_placeholders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_placeholder_associations',
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('placeholder_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['placeholder_id'], ['template_placeholders.id'], name='template_placeholder_associations_placeholder_id_fkey'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], name='template_placeholder_associations_template_id_fkey'),
    sa.PrimaryKeyConstraint('template_id', 'placeholder_id', name='template_placeholder_associations_pkey')
    )
    op.create_index('idx_template_placeholder_template_id', 'template_placeholder_associations', ['template_id'], unique=False)
    op.create_index('idx_template_placeholder_placeholder_id', 'template_placeholder_associations', ['placeholder_id'], unique=False)
    op.create_table('document_generations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='关联的案件ID'),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='关联的模板ID'),
    sa.Column('form_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='占位符填写数据，格式：{name: value}'),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='创建人ID'),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='最后更新人ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='document_generations_case_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['staffs.id'], name='document_generations_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], name='document_generations_template_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staffs.id'], name='document_generations_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_generations_pkey'),
    sa.UniqueConstraint('case_id', 'template_id', name='uq_case_template')
    )
    op.create_index('ix_document_generations_template_id', 'document_generations', ['template_id'], unique=False)
    op.create_index('ix_document_generations_id', 'document_generations', ['id'], unique=False)
    op.create_index('ix_document_generations_case_id', 'document_generations', ['case_id'], unique=False)
    op.create_index('idx_document_generations_template_id', 'document_generations', ['template_id'], unique=False)
    op.create_index('idx_document_generations_case_id', 'document_generations', ['case_id'], unique=False)
    op.create_table('template_placeholders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='占位符类型：text, textarea, select, radio, checkbox, date, number, file'),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='选项列表（用于 select, radio, checkbox 类型）'),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='创建人ID'),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='更新人ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='占位符名称（如：{{姓名}} 对应 name 字段）'),
    sa.Column('applicable_template_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='适用的模板类型：要素式/陈述式/通用（None表示通用，适用于所有类型）'),
    sa.ForeignKeyConstraint(['created_by_id'], ['staffs.id'], name='template_placeholders_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staffs.id'], name='template_placeholders_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='template_placeholders_pkey'),
    sa.UniqueConstraint('name', 'applicable_template_category', name='uq_template_placeholders_name_category')
    )
    op.create_index('ix_template_placeholders_type', 'template_placeholders', ['type'], unique=False)
    op.create_index('ix_template_placeholders_name', 'template_placeholders', ['name'], unique=False)
    op.create_index('ix_template_placeholders_id', 'template_placeholders', ['id'], unique=False)
    op.create_index('ix_template_placeholders_applicable_template_category', 'template_placeholders', ['applicable_template_category'], unique=False)
    op.create_index('idx_template_placeholders_name', 'template_placeholders', ['name'], unique=False)
    op.create_table('document_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='文书模板名称'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='文书模板描述'),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='分类名称'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='状态：draft/published'),
    sa.Column('prosemirror_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='ProseMirror JSON 格式的文档内容'),
    sa.Column('docx_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='原始 DOCX 文件在 COS 中的 URL'),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='创建人ID'),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='更新人ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('page_layout', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='页面布局设置（页边距、行间距等）'),
    sa.ForeignKeyConstraint(['created_by_id'], ['staffs.id'], name='document_templates_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staffs.id'], name='document_templates_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_templates_pkey')
    )
    op.create_index('ix_document_templates_status', 'document_templates', ['status'], unique=False)
    op.create_index('ix_document_templates_name', 'document_templates', ['name'], unique=False)
    op.create_index('ix_document_templates_id', 'document_templates', ['id'], unique=False)
    op.create_index('ix_document_templates_category', 'document_templates', ['category'], unique=False)
    op.create_index('idx_document_templates_status', 'document_templates', ['status'], unique=False)
    op.create_index('idx_document_templates_name', 'document_templates', ['name'], unique=False)
    op.create_index('idx_document_templates_category', 'document_templates', ['category'], unique=False)
    # ### end Alembic commands ###
