"""Add page_layout field to DocumentTemplate

Revision ID: e2bbb496ed87
Revises: a051e30d97c5
Create Date: 2025-12-11 13:58:21.708297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bbb496ed87'
down_revision: Union[str, Sequence[str], None] = 'a051e30d97c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_templates', sa.Column('page_layout', sa.JSON(), nullable=True, comment='页面布局设置（页边距、行间距等）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_templates', 'page_layout')
    # ### end Alembic commands ###
