"""new field sequence_number

Revision ID: e48a96b183c8
Revises: 08ef159b2321
Create Date: 2025-11-04 13:56:35.625297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48a96b183c8'
down_revision: Union[str, Sequence[str], None] = '08ef159b2321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_card_evidence_association', sa.Column('sequence_number', sa.Integer(), nullable=False, comment='引用证据的顺序序号，从0开始'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_card_evidence_association', 'sequence_number')
    # ### end Alembic commands ###
