"""简化占位符模型

Revision ID: e6f347101834
Revises: 6bf163929e0b
Create Date: 2025-11-21 17:18:16.923649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f347101834'
down_revision: Union[str, Sequence[str], None] = '6bf163929e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_generations_case_id'), 'document_generations', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_generations_template_id'), 'document_generations', ['template_id'], unique=False)
    op.add_column('template_placeholders', sa.Column('name', sa.String(length=100), nullable=False, comment='占位符名称（唯一，如：{{姓名}} 对应 name 字段）'))
    op.drop_index('idx_template_placeholders_placeholder_name', table_name='template_placeholders')
    op.drop_index('ix_template_placeholders_placeholder_name', table_name='template_placeholders')
    op.create_index('idx_template_placeholders_name', 'template_placeholders', ['name'], unique=False)
    op.create_index(op.f('ix_template_placeholders_name'), 'template_placeholders', ['name'], unique=True)
    op.drop_column('template_placeholders', 'default_value')
    op.drop_column('template_placeholders', 'required')
    op.drop_column('template_placeholders', 'placeholder_name')
    op.drop_column('template_placeholders', 'hint')
    op.drop_column('template_placeholders', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_placeholders', sa.Column('label', sa.VARCHAR(length=150), autoincrement=False, nullable=True, comment='占位符显示名称'))
    op.add_column('template_placeholders', sa.Column('hint', sa.TEXT(), autoincrement=False, nullable=True, comment='提示文本'))
    op.add_column('template_placeholders', sa.Column('placeholder_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='占位符名称（唯一，如：name, date, creditor_gender）'))
    op.add_column('template_placeholders', sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否必填'))
    op.add_column('template_placeholders', sa.Column('default_value', sa.TEXT(), autoincrement=False, nullable=True, comment='默认值'))
    op.drop_index(op.f('ix_template_placeholders_name'), table_name='template_placeholders')
    op.drop_index('idx_template_placeholders_name', table_name='template_placeholders')
    op.create_index('ix_template_placeholders_placeholder_name', 'template_placeholders', ['placeholder_name'], unique=False)
    op.create_index('idx_template_placeholders_placeholder_name', 'template_placeholders', ['placeholder_name'], unique=False)
    op.drop_column('template_placeholders', 'name')
    op.drop_index(op.f('ix_document_generations_template_id'), table_name='document_generations')
    op.drop_index(op.f('ix_document_generations_case_id'), table_name='document_generations')
    # ### end Alembic commands ###
