"""update case status

Revision ID: f115beb00e7c
Revises: 87a8a74ff1f5
Create Date: 2025-09-15 16:43:10.618303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'f115beb00e7c'
down_revision: Union[str, Sequence[str], None] = '87a8a74ff1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='casestatus',
        new_values=['DRAFT', 'ACCEPTED', 'DOCUMENTS_COMPLETE', 'FILING_SUBMITTED', 'FILING_APPROVED', 'FILING_REJECTED', 'PAYMENT_NOTIFIED', 'PAYMENT_COMPLETED', 'MEDIATION_COMPLETED', 'SUMMONS_DELIVERED', 'JUDGMENT_RENDERED', 'ENFORCEMENT_APPLIED', 'ENFORCEMENT_DOCUMENT_SIGNED', 'ENFORCEMENT_DOCUMENT_SUBMITTED', 'ENFORCEMENT_APPROVED', 'ENFORCEMENT_TERMINATED'],
        affected_columns=[TableReference(table_schema='public', table_name='cases', column_name='case_status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='casestatus',
        new_values=['DRAFT', 'INFO_ENTERED', 'EVIDENCE_ANNOTATED', 'DOCUMENTS_GENERATED'],
        affected_columns=[TableReference(table_schema='public', table_name='cases', column_name='case_status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
