"""Add page_layout to document_drafts

Revision ID: f1234567890a
Revises: e2bbb496ed87
Create Date: 2025-12-11 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1234567890a'
down_revision: Union[str, Sequence[str], None] = 'e2bbb496ed87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_drafts', sa.Column('page_layout', sa.JSON(), nullable=True, comment='页面布局设置（页边距、行间距等）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_drafts', 'page_layout')
    # ### end Alembic commands ###
