"""refactor_evidence_card_use_evidence_ids_field

Revision ID: fc24043d1138
Revises: a46c86c92117
Create Date: 2025-11-06 14:21:14.352526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc24043d1138'
down_revision: Union[str, Sequence[str], None] = 'a46c86c92117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_card_evidence_association')
    op.alter_column('evidence_card_slot_assignments', 'template_id',
               existing_type=sa.VARCHAR(length=200),
               comment='模板ID，如：民间借贷纠纷-微信聊天记录主证据-个人-个人-卡片槽位模板',
               existing_nullable=False)
    op.alter_column('evidence_card_slot_assignments', 'slot_id',
               existing_type=sa.VARCHAR(length=200),
               comment='槽位ID，格式：slot::{role}::{cardType}::{index}',
               existing_nullable=False)
    op.alter_column('evidence_card_slot_assignments', 'card_id',
               existing_type=sa.INTEGER(),
               comment='关联的卡片ID，null表示该槽位未放置卡片',
               existing_nullable=True)
    op.add_column('evidence_cards', sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='引用的证据ID列表，按顺序存储'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_cards', 'evidence_ids')
    op.alter_column('evidence_card_slot_assignments', 'card_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联的卡片ID，null表示该槽位未放置卡片',
               existing_nullable=True)
    op.alter_column('evidence_card_slot_assignments', 'slot_id',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='槽位ID，格式：slot::{role}::{cardType}::{index}',
               existing_nullable=False)
    op.alter_column('evidence_card_slot_assignments', 'template_id',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='模板ID，如：民间借贷纠纷-微信聊天记录主证据-个人-个人-卡片槽位模板',
               existing_nullable=False)
    op.create_table('evidence_card_evidence_association',
    sa.Column('evidence_card_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='证据卡片ID，null表示卡片已删除'),
    sa.Column('evidence_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='证据ID，null表示证据已删除'),
    sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=False, comment='引用证据的顺序序号，从0开始'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['evidence_card_id'], ['evidence_cards.id'], name=op.f('evidence_card_evidence_association_evidence_card_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], name=op.f('evidence_card_evidence_association_evidence_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('evidence_card_evidence_association_pkey'))
    )
    # ### end Alembic commands ###
